name: Kernel Builds

on:
  workflow_dispatch:

jobs:
  stock-kernel:
    name: Stock Kernel Build
    runs-on: ubuntu-20.04
    steps:
      - name: Build Stock Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/galaxybuild-project/android_kernel_samsung_msm6375
          kernel-branch: stock
          config: a23xq_eur_open_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          aosp-clang-version: r383902b1

  kernel-su-next-susfs:
    name: Kernel SU Next SuSFS Build
    runs-on: ubuntu-20.04
    steps:
      - name: Build KernelSU SuSFS Patch
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/galaxybuild-project/android_kernel_samsung_msm6375
          kernel-branch: next-susfs
          config: a23xq_eur_open_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          aosp-clang-version: r383902b1
